author = Artur Tarassow
email = atecon@posteo.de
version = 0.5
date = 2019-12-18
description = Write matrix as dataset to some file (e.g. csv, gdt)
tags = C81
min-version = 2018a
public = mat2data
depends = string_utils
help = mat2data_help.txt
sample-script = mat2data_sample.inp
