author = Artur Tarassow
email = atecon@posteo.de
version = 0.5
date = 2019-12-13
description = Write matrix to csv file
tags = C81
min-version = 2018a
data-requirement = no-data-ok
public = MwriteCsv
help = MwriteCsv_help.txt
sample-script = MwriteCsv_sample.inp
