author = Artur Tarassow
email = atecon@posteo.de
version = 0.5
date = 2019-12-17
description = Write matrix as dataset to some file (e.g. csv, gdt)
tags = C81
min-version = 2018a
data-requirement = no-data-ok
public = Mat2Datafile
depends = string_utils
help = MwriteCsv_help.txt
sample-script = MwriteCsv_sample.inp
